import = [
  "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true
option_as_alt = "Both"
opacity = 0.95

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 4
y = 4
