# thePrimeagen's tmux config
set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0
setw -g mouse on

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'

set -g history-limit 100000

bind r source-file ~/.config/tmux/tmux.conf
set -g base-index 1

# re number the windows on creation/deletion
set -g renumber-windows on

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Smart pane switching with awareness of Vim splits.
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"

# Use C-w as prefix for pane navigation
bind-key -n C-w switch-client -T pane-nav

# Pane navigation with vim awareness
bind-key -T pane-nav h if-shell "$is_vim" 'send-keys C-w h' 'select-pane -L'
bind-key -T pane-nav j if-shell "$is_vim" 'send-keys C-w j' 'select-pane -D'
bind-key -T pane-nav k if-shell "$is_vim" 'send-keys C-w k' 'select-pane -U'
bind-key -T pane-nav l if-shell "$is_vim" 'send-keys C-w l' 'select-pane -R'
bind-key -T pane-nav \\ if-shell "$is_vim" 'send-keys C-w \\' 'select-pane -l'

# For copy mode
bind-key -T copy-mode-vi C-w switch-client -T pane-nav-copy
bind-key -T pane-nav-copy h select-pane -L
bind-key -T pane-nav-copy j select-pane -D
bind-key -T pane-nav-copy k select-pane -U
bind-key -T pane-nav-copy l select-pane -R
bind-key -T pane-nav-copy \\ select-pane -l

# appearance
set -gw clock-mode-colour "blue"
set -gw pane-active-border-style "fg=magenta"
set -gw pane-border-style "fg=brightblack"
set -gw window-status-activity-style "fg=blue"
set -gw window-status-bell-style "fg=yellow"
set -gw window-status-current-format " #F#I:#W "
set -gw window-status-current-style "fg=green,reverse"
set -gw window-status-format " #F#I:#W "
set -gw window-status-last-style "fg=green"
set -gw window-status-separator ""
set -gw window-status-style ""

set -g display-panes-active-colour "magenta"
set -g display-panes-colour "brightblack"
set -g message-command-style ""
set -g message-style ""
set -g status-left "#[range=user|switch_session] #S #[norange]"
set -g status-left-style "fg=blue bold reverse"
set -g status-right "%Y-%m-%d %H:%M #{tmux_mode_indicator}"
set -g status-style ""

# resize pane
bind -r -Tnav C-M-h resize-pane -L 10
bind -r       M-h resize-pane -L 10
bind -r -Tnav M-j resize-pane -D 5
bind -r       M-j resize-pane -D 5
bind -r -Tnav M-k resize-pane -U 5
bind -r       M-k resize-pane -U 5
bind -r -Tnav M-l resize-pane -R 10
bind -r       M-l resize-pane -R 10

# Undercurl
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

set-option -ga terminal-overrides ",xterm-256color:Tc"

# source ~/.config/tmux/tokyonight_night.tmux

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin "janoamaral/tokyo-night-tmux"

run '~/.tmux/plugins/tpm/tpm'
